export let PASSWORD_GENERATORS = {
	GENERATING_PASSWORD : 'GENERATING_PASSWORD',
	GENERATED_PASSWORD : 'GENERATED_PASSWORD',
	CHANGE_OPTION :'CHANGE_OPTION',
	CHANGE_INCLUDE : 'CHANGE_INCLUDE',
	RESETPASSWORD : 'RESETPASSWORD'
};